# -*- coding: utf-8 -*-
"""Content for the three retreat pages.

Copy is drawn from the existing estanciavik.com, playavik.com and
bahiavik.com sites and from the VIK José Ignacio brief. Facts — acreage,
architects, room counts, addresses — are taken from those sources rather
than written, so nothing here needs re-checking with the client.

Authored by Nicolás Castillo · @donhkoland
"""
from tools_property import HEAD, tile, slide, card, film_card, paras

DATA = {}

# ── Estancia VIK ────────────────────────────────────────────────
DATA["estancia"] = dict(
    key="estancia", name="Estancia VIK", shortname="Estancia",
    file="estancia.html", ribbon="#1E1E1E",
    eyebrow="Retreat 01 · Countryside · José Ignacio",
    meta="Estancia VIK José Ignacio — 4,000 acres of Uruguayan countryside, twelve artist suites, horses and open-fire dining at El Asador.",
    hero1="estancia__Estancia-IMG_7582-min-1",
    hero2="estancia__Chapel-IMG_0177-min",
    video="countryside",
    standfirst="Romantic, rustic and traditional. A classic Spanish colonial estancia on four thousand acres, paying homage to <em>Uruguay's nature</em>, architecture, art and design.",
    about_title="A haven of art, nature and high design.",
    about_kicker="White adobe,<br>red tin, <em>open country</em>",
    about_body=paras([
        "Estancia VIK José Ignacio was a collaboration between the creators, Carrie and Alex Vik, and the Uruguayan architect Marcelo Daglio — a traditional Spanish-style estancia of white adobe walls and red tin roofs, with covered walkways linking courtyards and gardens.",
        "Within the 50,000 square feet of the structure, more than half is outdoor space: interior patios, courtyards, covered walkways and a large organic herb garden. The patios carry outdoor seating, sculpture installations and shade from the afternoon.",
        "The south side opens onto a grass garden and a twenty-metre pool cut from Absolute Nero stone. The floor of the pool is dotted with fibre-optic lights that mirror the constellations above it.",
    ]),
    spaces_title="Galpón, chapel, cellar, gardens.",
    gallery="\n".join([
        slide("estancia/chapel-img_0177-min.jpg", "The Chapel"),
        slide("estancia/gardens-img_1111-min.jpg", "Patios & Gardens"),
        slide("estancia/bbq-img_7731.jpg", "The Parrillero"),
        slide("estancia/pool-img_1630-min.jpg", "Absolute Nero pool"),
        slide("estancia/gameroom-img_4145-min.jpg", "Game Room"),
        slide("estancia/sculpture-img_1789.jpg", "Sculpture"),
        slide("estancia/entrance-img_0003-min.jpg", "The Entrance"),
        slide("estancia/estanciavik-0323-min.jpg", "The Grounds"),
    ]),
    location_title="Four thousand acres, a mile from the Atlantic.",
    location_lead="The Estancia sits in the rolling countryside of José Ignacio, bordering the Arroyo and the Laguna José Ignacio, which meet the Southern Atlantic just a mile away as the crow flies.",
    address="Cam. Eugenio Saiz Martínez Km 8, 20402 Faro de José Ignacio, Maldonado",
    from_pdp="50 min by road",
    from_mvd="2 h 15 by road",
    roomcount="12 suites",
    rooms_title="Twelve suites, twelve artists.",
    rooms_lead="Two wings, six suites each. Four Master Suites of 900 square feet on the upper level, eight Guest Suites of 500 on the ground floor — every one designed around original work by a leading contemporary Uruguayan artist, conceived for that particular room.",
    tiles="\n".join([
        tile("estancia/vik-master-suite.jpg", "Master Suite VIK", "Master · East Wing, upper level", "King bed, 85 m² bathroom, living room with fireplace, and a private terrace with river and landscape views. Work by Hugo Longa.", "Master Suites", ['estancia/gardens-img_1111-min.jpg', 'estancia/entrance-img_0003-min.jpg']),
        tile("estancia/daglio-img_0263.jpg", "Master Suite Daglio", "Master · upper level", "Named for the architect of the house. Fireplace, private terrace and an outdoor shower onto the bucolic landscape.", "Master Suites", ['estancia/bbq-img_7731.jpg', 'estancia/gardens-img_1111-min.jpg']),
        tile("estancia/legrand_1.jpg", "Master Suite Legrand", "Master · upper level", "Double aspect — morning light on one side, the long evening on the other. Outdoor shower on the patio.", "Master Suites", ['estancia/chapel-img_0177-min.jpg', 'estancia/bbq-img_7731.jpg']),
        tile("estancia/seveso-img_9629.jpg", "Master Suite Seveso", "Master · upper level", "A master suite at the quiet end of the wing, facing the open field.", "Master Suites", ['estancia/north-garden-to-living-room-1.jpg', 'estancia/chapel-img_0177-min.jpg']),
        tile("estancia/amengal-img_8677.jpg", "Amengual Suite", "Guest · ground level", "One artist, one room, floor to ceiling. Private access to the exterior patios.", "Guest Suites", ['estancia/sculpture-img_1789.jpg', 'estancia/north-garden-to-living-room-1.jpg']),
        tile("estancia/barea-img_0313.jpg", "Barea Suite", "Guest · ground level", "Painted in full by Barea, opening onto the gardens and the pool.", "Guest Suites", ['estancia/estancia-img_0005.jpg', 'estancia/sculpture-img_1789.jpg']),
        tile("estancia/cardozo-img_9671.jpg", "Cardozo Suite", "Guest · ground level", "Over the south gardens, with the horses visible from the bed.", "Guest Suites", ['estancia/estanciavik-0323-min.jpg', 'estancia/estancia-img_0005.jpg']),
        tile("estancia/badaro-img_7678.jpg", "Badaro Suite", "Guest · ground level", "Warm, low and enclosed — the suite guests ask for in winter.", "Guest Suites", ['estancia/pool-img_1630-min.jpg', 'estancia/estanciavik-0323-min.jpg']),
        tile("estancia/musso-img_0204.jpg", "Musso Suite", "Guest · ground level", "Musso's work across every surface, including the ceiling.", "Guest Suites", ['estancia/entrance-to-living-room.jpeg', 'estancia/pool-img_1630-min.jpg']),
        tile("estancia/trujillo-img_0201.jpg", "Trujillo Suite", "Guest · ground level", "Bold and graphic — the most photographed room in the house.", "Guest Suites", ['estancia/gameroom-img_4145-min.jpg', 'estancia/entrance-to-living-room.jpeg']),
        tile("estancia/turell_old1.jpg", "Turell Suite", "Guest · ground level", "Light handled as a material. Best at the end of the afternoon.", "Guest Suites", ['estancia/estancia-img_0004.jpg', 'estancia/gameroom-img_4145-min.jpg']),
        tile("estancia/duarte-dsc_0061.jpg", "Duarte Suite", "Guest · ground level", "Opening straight onto the north garden and the long lawn.", "Guest Suites", ['estancia/entrance-img_0003-min.jpg', 'estancia/estancia-img_0004.jpg']),
    ]),
    restaurant="El Asador",
    dining_anchor="el-asador",
    dining_img="estancia__BBQ-IMG_7731",
    dining_cuisine="Open fire · farm to table",
    dining_hours="Lunch and dinner, daily",
    dining_body=paras([
        "The most authentic Uruguayan BBQ — family style or three courses, in settings where gaucho tradition sits alongside contemporary Uruguayan art.",
        "Served in the art-filled Parrillero, in the brick vaulted dining room, or by the Absolute Nero pool overlooking the pastoral landscape, the river and the Laguna José Ignacio. Chef Marcelo Betancourt and his team cook from the market and the Estancia gardens, with VIK wine from the Millahue Valley on every table.",
    ], lead=False),
    exp_title="Marlboro country meets a laid-back St Tropez.",
    exp_lead="The guest experience at Estancia VIK is one of the most unusual in the world. Everything below is arranged by your Journey Designer.",
    cards="\n".join([
        film_card("countryside", "Daily", "All levels", "Ride out with the gauchos.",
                  "Criollo and Quarter horses across open pampas, from the Estancia to the lagoon. The signature experience of the house, and the reason many guests come back.",
                  "Reserve a ride", "#contact"),
        card("estancia/gardens-img_1111-min.jpg", "Nature", "Half day", "Wildlife, birds and water.",
             "Mountain bike, hike, canoe and fish in the Arroyo and the Laguna de José Ignacio.",
             "Plan a day", "#contact"),
        card("estancia/pool-img_1630-min.jpg", "Sport", "On site", "Grass courts and golf.",
             "Tennis on the Estancia's grass courts, water sports, and excellent 18-hole courses nearby.",
             "Ask the team", "#contact"),
        card("estancia/chapel-img_0177-min.jpg", "Culture", "By arrangement", "The chapel, the galpón, the cellar.",
             "A private tour of the house with its curator — the commissioned works, the wine cellar and the chapel on the hill.",
             "Arrange a visit", "#contact"),
    ]),
    book_title="Twelve suites.<br>One <em>estancia</em>.",
)

# ── Playa VIK ───────────────────────────────────────────────────
DATA["playa"] = dict(
    key="playa", name="Playa VIK", shortname="Playa",
    file="playa.html", ribbon="#1E1E1E",
    eyebrow="Retreat 02 · Oceanfront · José Ignacio",
    meta="Playa VIK José Ignacio — Carlos Ott architecture, a titanium Sculpture building, six casas with living roofs and CieloMar over the Atlantic.",
    hero1="playa__80c9a60ef2cc735699a0e504cbfa54955f3113fe",
    hero2="playa__Casas-main-scaled",
    video="landscape",
    standfirst="Striking architecture on the most coveted point of the Uruguayan coastline, with panoramic ocean views, an important art collection and <em>magnificent sunsets</em>.",
    about_title="A collaboration with Carlos Ott.",
    about_kicker="Titanium, bronze<br>and <em>the ocean</em>",
    about_body=paras([
        "Playa VIK is a collaboration between the creators, Carrie and Alex Vik, and the internationally renowned Uruguayan architect Carlos Ott. The avant-garde beachfront retreat is built around a central Sculpture building, which holds an important collection of international and contemporary Uruguayan art.",
        "The building's 55-foot inclined façade opens through a vast sliding wall of glass onto the coastline. The entrance is a two-storey curved and inclined glass façade with a monumental sculpted bronze door by Pablo Atchugarry — a modern reading of Ghiberti's doors at the Baptistery in Florence.",
        "The lateral walls and roof are double-curved titanium panels. Patagonian ebony floors run throughout, extending from the living room to the pool terrace and blurring the line between interior and exterior.",
    ]),
    spaces_title="Sculpture, pool, spa, brasero.",
    gallery="\n".join([
        slide("playa/casas-main-scaled.jpg", "The Casas"),
        slide("playa/pool-img_0520.jpg", "The Pool"),
        slide("playa/spa-img_0817.jpg", "The Spa"),
        slide("playa/sculpture-img_1227.jpg", "Sculpture"),
        slide("playa/parillero_playa-vik-934.jpg", "The Parrillero"),
        slide("playa/gameroom_02.jpg", "Game Room"),
        slide("playa/gym_img_1967.jpg", "The Gym"),
        slide("playa/home-img_1789.jpg", "The Point"),
    ]),
    location_title="On the point, above Mansa beach.",
    location_lead="Playa VIK sits on the Mansa beach in the bohemian village of José Ignacio, twelve miles north-east of Punta del Este, with a panoramic view of the landscape and the ocean beyond.",
    address="Los Cisnes esq. Los Horneros, 20402 José Ignacio, Maldonado",
    from_pdp="35 min by road",
    from_mvd="2 h by road",
    roomcount="Suites &amp; casas",
    rooms_title="The Sculpture, and six casas.",
    rooms_lead="Suites within the Sculpture building, flanked by six casas of two or three bedrooms each with private gardens. Every casa has a fireplace and a distinct art-filled interior; retractable windows open the rooms onto the gardens, under living roofs of rayitos del sol wildflowers.",
    tiles="\n".join([
        tile("playa/casas-main-scaled.jpg", "The Casas", "Playa VIK · two and three bedrooms", "Six casas flanking the Sculpture, each with a fireplace, a private garden and fully retractable windows onto it.", "Suites", ['playa/pool-img_0520.jpg', 'playa/gym_img_1967.jpg']),
        tile("playa/casa_blanca_img_0860.jpg", "Casa Blanca", "Playa VIK · casa", "Bright, low and open to the garden, with the ocean audible from the bed.", "Casas", ['playa/home-img_1789.jpg', 'playa/casas-main-scaled.jpg']),
        tile("playa/gardenview-living-scaled.jpg", "Garden View Living", "Playa VIK · casa", "The living space opening straight into the private garden through a retractable wall.", "Casas", ['playa/sculpture-img_1227.jpg', 'playa/dscf3708-hdr-scaled.jpg']),
        tile("playa/1_3_-acommodations-op3-1-scaled.jpg", "Sculpture Suites", "Playa VIK · main building", "Suites within the Sculpture, under the double-curved titanium roof and above the art collection.", "Suites", ['playa/dscf3708-hdr-scaled.jpg', 'playa/spa-img_0817.jpg']),
        tile("playa/dscf3708-hdr-scaled.jpg", "Ocean Suite", "Playa VIK · suite", "Facing the water, with Patagonian ebony floors running out to the terrace.", "Suites", ['playa/gym_img_1967.jpg', 'playa/casas-main-scaled.jpg']),
        tile("playa/dscf3770-hdr-scaled.jpg", "Terrace Suite", "Playa VIK · suite", "Opening onto the pool terrace and the long view down Playa Mansa.", "Suites", ['playa/dscf4068-hdr-scaled.jpg', 'playa/parillero_playa-vik-934.jpg']),
        tile("playa/dscf3917-hdr-scaled.jpg", "Garden Suite", "Playa VIK · suite", "Set into the planted roofscape, quiet and entirely private.", "Suites", ['playa/dscf3708-hdr-scaled.jpg', 'playa/sculpture-img_1227.jpg']),
        tile("playa/dscf4068-hdr-scaled.jpg", "Sunset Suite", "Playa VIK · suite", "Positioned for the hour Playa VIK is known for.", "Suites", ['playa/gameroom_02.jpg', 'playa/dscf3917-hdr-scaled.jpg']),
        tile("playa/dscf4341-hdr-scaled.jpg", "Art Suite", "Playa VIK · suite", "Built around a single commissioned work, as every VIK room is.", "Suites", ['playa/gardenview-living-scaled.jpg', 'playa/pool-img_0520.jpg']),
        tile("playa/1-11-de-12-scaled.jpg", "Casa Living", "Playa VIK · casa", "The shared living space of the casa, with fireplace and garden access.", "Casas", ['playa/sculpture-img_1227.jpg', 'playa/gardenview-living-scaled.jpg']),
        tile("playa/1-19-de-44-scaled.jpg", "Casa Bedroom", "Playa VIK · casa", "One of the two or three bedrooms within each casa.", "Casas", ['playa/dscf3917-hdr-scaled.jpg', 'playa/sculpture-img_1227.jpg']),
        tile("playa/1-26-de-44-scaled.jpg", "Casa Garden", "Playa VIK · casa", "Bougainvillea dividing one casa from the next, under the living roof.", "Casas", ['playa/gameroom_02.jpg', 'playa/sculpture-img_1227.jpg']),
    ]),
    restaurant="CieloMar",
    dining_anchor="cielomar",
    dining_img="playa__Parillero_Playa-Vik-934",
    dining_cuisine="Fish BBQ · coastal",
    dining_hours="Lunch and dinner, daily",
    dining_body=paras([
        "The signature fish BBQ and three-course meals overlooking the Southern Atlantic, with views down Playa Mansa to Punta del Este and to the fishing boats next door — where the chef chose the fish that morning.",
        "Sit in the Parrillero dining room, on the terrace above the beach, or at the brasero fire pit, with a glass of VIK wine. Sunset from CieloMar has been described as the best in José Ignacio.",
    ], lead=False),
    exp_title="Art, water and the last light.",
    exp_lead="Playa VIK is the quietest of the three houses. What happens here happens slowly, and is arranged by your Journey Designer.",
    cards="\n".join([
        film_card("landscape", "Daily", "1 h", "Walk the collection.",
                  "The Sculpture building, the Atchugarry bronze door, the casas and the sculpture terrace, with the house guide.",
                  "Join a walk", "#contact"),
        card("playa/spa-img_0817.jpg", "The Shack", "45'", "Recover, before dinner.",
             "Movement, strength, treatment and rest — nature-led wellbeing across the destination.",
             "Explore wellness", "wellness.html"),
        card("playa/pool-img_0520.jpg", "Sunset", "19:30", "The hour Playa is known for.",
             "The pool terrace, the brasero and the light going down over the point.",
             "Reserve a table", "dining.html#cielomar"),
        card("playa/parillero_playa-vik-934.jpg", "Culinary", "Evenings", "Fish BBQ at the brasero.",
             "The catch chosen that morning from the boats next door, cooked over the fire pit as the light goes down.",
             "Reserve", "dining.html#cielomar"),
    ]),
    book_title="The Sculpture.<br>And six <em>casas</em>.",
)

# ── Bahía VIK ───────────────────────────────────────────────────
DATA["bahia"] = dict(
    key="bahia", name="Bahía VIK", shortname="Bahía",
    file="bahia.html", ribbon="#1E1E1E",
    eyebrow="Retreat 03 · Playa Mansa · José Ignacio",
    meta="Bahía VIK José Ignacio — ten artist suites and fifteen design bungalows set into the dunes of Playa Mansa, with Zodiaco, pools and The Shack wellness.",
    hero1="bahia__1_BV-0439-scaled",
    hero2="bahia__CP-BahiaVik-0552-scaled",
    video="hero-brand",
    standfirst="Relaxed beach lifestyle, design-led architecture and social energy. Bungalows tucked into the breezy dunes of <em>Playa Mansa</em>, each one a different material and a different artist.",
    about_title="Fifteen bungalows in the dunes.",
    about_kicker="Adobe, corten,<br>zinc and <em>glass</em>",
    about_body=paras([
        "Bahía VIK José Ignacio is built around a collection of uniquely designed bungalows, several of them in privileged beachfront settings, and ten suites on the first and second floors of the main building.",
        "Each bungalow has a distinct exterior, an art-filled interior and its own design scheme — adobe, corten steel, zinc, glass, thatch, timber and stone. Tucked into the beach dunes, each one deliberately blends interior and exterior to encourage the maximum enjoyment of nature.",
        "Natural dunes covered in swaying beach grasses and local flora divide one bungalow from the next, so each keeps its own privacy while sharing the same stretch of the bay.",
    ]),
    spaces_title="Pools, patios, the dune and the bay.",
    gallery="\n".join([
        slide("bahia/cp-bahiavik-0552-scaled.jpg", "Interiors"),
        slide("bahia/cp-bahiavik-0562-scaled.jpg", "The Dunes"),
        slide("bahia/cp-bahiavik-0549-scaled.jpg", "The Terrace"),
        slide("bahia/vik_food08.jpg", "Zodiaco"),
        slide("bahia/cp-bahiavik-0546-scaled.jpg", "The Pools"),
        slide("bahia/dscf5297-min.jpg", "Playa Mansa"),
        slide("bahia/36_bv_img_0070-1-scaled.jpg", "The Main Building"),
        slide("bahia/16_bv-1106-scaled.jpg", "The Bay"),
    ]),
    location_title="In the dunes, on the calm side.",
    location_lead="Bahía VIK sits on Ruta 10 in the dunes of Playa Mansa — the sheltered side of José Ignacio, where the water stays calm and the beach is walkable from every bungalow.",
    address="Ruta 10, 20402 Faro de José Ignacio, Maldonado",
    from_pdp="40 min by road",
    from_mvd="2 h 10 by road",
    roomcount="25 rooms",
    rooms_title="Ten suites, fifteen bungalows.",
    rooms_lead="Ten suites in the main building, each created by a different Uruguayan artist, with views over the gardens and the ocean. Fifteen bungalows in the dunes — two of five bedrooms, one of three, one of four, and eleven with two bedrooms plus a living area, each suite with its own bathroom.",
    tiles="\n".join([
        tile("bahia/adobe-0098.jpg", "Bungalow Adobe", "Bahía VIK · bungalow", "Hand-built earth walls and a grass roof, with the dune between you and the bay. Two suites and a living room, all connectable.", "Bungalows", ['bahia/cp-bahiavik-0552-scaled.jpg', 'bahia/16_bv-1106-scaled.jpg']),
        tile("bahia/corten-0368.jpg", "Bungalow Corten", "Bahía VIK · bungalow", "Weathered steel that keeps changing colour through the season.", "Bungalows", ['bahia/dsc_3451-min.jpg', 'bahia/cp-bahiavik-0552-scaled.jpg']),
        tile("bahia/madera-0122.jpg", "Bungalow Madera", "Bahía VIK · bungalow", "All timber, warm and close, with a deck straight onto the sand path.", "Bungalows", ['bahia/cp-bahiavik-0562-scaled.jpg', 'bahia/dsc_3451-min.jpg']),
        tile("bahia/piedra-0121.jpg", "Bungalow Piedra", "Bahía VIK · bungalow", "Local stone, cool at midday, one of the largest on the dune.", "Bungalows", ['bahia/dscn2725-scaled.jpg', 'bahia/cp-bahiavik-0562-scaled.jpg']),
        tile("bahia/quincha-0102.jpg", "Bungalow Quincha", "Bahía VIK · bungalow", "Thatch and light timber — the most Uruguayan of the fifteen.", "Bungalows", ['bahia/dscf5297-min.jpg', 'bahia/dscn2725-scaled.jpg']),
        tile("bahia/titanio-0086.jpg", "Bungalow Titanio", "Bahía VIK · bungalow", "A titanium skin, echoing the roof at Playa VIK across the point.", "Bungalows", ['bahia/dscn2783-scaled.jpg', 'bahia/dscf5297-min.jpg']),
        tile("bahia/vidrio-0092.jpg", "Bungalow Vidrio", "Bahía VIK · bungalow", "Glass on three sides. Nothing between the bed and the bay.", "Bungalows", ['bahia/36_bv_img_0070-1-scaled.jpg', 'bahia/dscn2783-scaled.jpg']),
        tile("bahia/zinc-negro-0330.jpg", "Bungalow Zinc Negro", "Bahía VIK · bungalow", "Black zinc, low in the dune, almost invisible from the beach.", "Bungalows", ['bahia/cp-bahiavik-0546-scaled.jpg', 'bahia/36_bv_img_0070-1-scaled.jpg']),
        tile("bahia/zinc-marron-0118.jpg", "Bungalow Zinc Marrón", "Bahía VIK · bungalow", "The warmer of the two zinc houses, facing the afternoon.", "Bungalows", ['bahia/dsc_3096-min.jpg', 'bahia/cp-bahiavik-0546-scaled.jpg']),
        tile("bahia/duna-0340.jpg", "Bungalow Duna", "Bahía VIK · bungalow", "Built into the dune itself, with the roof planted over.", "Bungalows", ['bahia/cp-bahiavik-0549-scaled.jpg', 'bahia/dsc_3096-min.jpg']),
        tile("bahia/chapaazul.jpg", "Bungalow Chapa Azul", "Bahía VIK · bungalow", "Blue sheet metal — the loudest and most loved of the row.", "Bungalows", ['bahia/dscn2740-scaled.jpg', 'bahia/cp-bahiavik-0549-scaled.jpg']),
        tile("bahia/img_1647-eva2.jpg", "Suite Eva", "Bahía VIK · main building", "Above the pool, facing the bay, with the gardens below.", "Suites", ['bahia/cp-bahiavik-0593-scaled.jpg', 'bahia/cp-bahiavik-0598.jpg']),
        tile("bahia/img_1550-guerra5.jpg", "Suite Guerra", "Bahía VIK · main building", "Guerra's work throughout, with a terrace over Playa Mansa.", "Suites", ['bahia/img_1589-guerra12.jpg', 'bahia/img_1589-guerra12-1.jpg']),
        tile("bahia/img_1664-patrone1.jpg", "Suite Patrone", "Bahía VIK · main building", "Quiet, at the end of the corridor, with the best morning light.", "Suites", ['bahia/dsc_3451-min.jpg', 'bahia/16_bv-1106-scaled.jpg']),
        tile("bahia/img_1717-escardo3.jpg", "Suite Escardó", "Bahía VIK · main building", "Escardó from wall to wall. Two beds, ideal for families.", "Suites", ['bahia/cp-bahiavik-0554-scaled.jpg', 'bahia/cp-bahiavik-0562-scaled.jpg']),
        tile("bahia/img_1624-lopezlaje3.jpg", "Suite López Lage", "Bahía VIK · main building", "One of the strongest commissions in the collection.", "Suites", ['bahia/cp-bahiavik-0562-1-scaled.jpg', 'bahia/dscn2725-scaled.jpg']),
    ]),
    restaurant="Zodiaco",
    dining_anchor="zodiaco",
    dining_img="bahia__vik_food08",
    dining_cuisine="Uruguayan · bay-side",
    dining_hours="All day, daily",
    dining_body=paras([
        "Dining at Bahía VIK highlights the surrounding terroir through locally grown and produced ingredients, with a continued emphasis on authentic Uruguayan cuisine.",
        "Eat on the expansive outdoor terrace, by one of the pools, in the open-air patio or in the dining room. The menu runs on fresh fish and seafood, local fruit and vegetables, and home-made breads and pastries — with VIK wine from the sister vineyard in Millahue.",
    ], lead=False),
    exp_title="The bay, the pools and the people.",
    exp_lead="Bahía is the most social of the three houses. Everything below is arranged by your Journey Designer.",
    cards="\n".join([
        film_card("wellness", "The Shack", "45'", "Move, then recover.",
                  "Movement, strength, treatments and recovery on the dune deck — the wellness centre of the destination, open to guests of all three retreats.",
                  "Explore wellness", "wellness.html"),
        card("bahia/cp-bahiavik-0546-scaled.jpg", "Daily", "All ages", "Pool life.",
             "The pools, the terrace and the calm water of Playa Mansa, steps from every bungalow.",
             "Plan a day", "#contact"),
        card("bahia/cp-bahiavik-0549-scaled.jpg", "Pavilion VIK", "Events", "Celebrate on the ocean.",
             "The primary oceanfront event and cultural venue of VIK José Ignacio.",
             "Plan an event", "celebrate.html"),
        card("bahia/dscf5297-min.jpg", "Water", "Daily", "The calm side.",
             "Paddle, swim and sail from Playa Mansa, where the bay stays flat long after the ocean side has turned.",
             "Plan a day", "#contact"),
    ]),
    book_title="Ten suites.<br>Fifteen <em>bungalows</em>.",
)

if __name__ == "__main__":
    import os
    base = os.path.dirname(os.path.abspath(__file__))
    for k, d in DATA.items():
        out = os.path.join(base, d["file"])
        with open(out, "w", encoding="utf-8") as f:
            f.write(HEAD.format(**d))
        print("%-14s %6.1f KB  %2d rooms" % (d["file"], os.path.getsize(out) / 1024, d["tiles"].count("wall-tile")))
